---
title: "R Notebook"
output: html_notebook
---
```{r}
library(plot0)
library(ggplot2)
```

```{r}
# Creating dataframes
filepath <- paste0(getwd())
table_1_filename <- 'table1.csv'
df_table1 <- MyFread(table_1_filename, filepath)
table_2_filename <- 'table2_concentration_metric.csv'
df_table2 <- MyFread(table_2_filename, filepath)
table_3_filename <- 'table3.csv'
df_table3 <- MyFread(table_3_filename, filepath)
```
# Descriptive statistics figures

# Table 2 Figures
```{r}
row_to_keep = c(TRUE, TRUE, TRUE, TRUE, FALSE)
df_table2_plot = df_table2[row_to_keep,]
df_table2_plot[4, 1] <- "Gagne score"
```

```{r}
table2_boxplot <- ggplot(df_table2_plot, aes(x = predictor, y = `Race black`, fill=predictor)) +
  geom_bar(position=position_dodge(), stat="identity",
           colour='black') +
  geom_errorbar(aes(ymin=`Race black` - `Race black SE`, ymax=`Race black` + `Race black SE`), width=.2)
table2_boxplot <- table2_boxplot + labs(title="Fraction of Black Patients in the group with the highest risk by predictor")
```


```{r}
table2_boxplot
```
```{r}
df_table3
```

